### ISSUE TITLE
Support for handling py_library dependencies

### ISSUE THREAD

**Issue by svermeulen** [cedarai/rules_pyvenv#1] opened 2022-06-18 22:49 UTC
This is great, thanks for sharing.  One thing that appears to be missing is hooking up any `py_library` dependencies as part of the generated venv

**Comment by jvolkman** [comment] 2022-11-23 18:00
Hi @svermeulen - I'd like to address this issue but want to make sure I understand your problem first. Would it be possible to put together a small reproducible example?

If not - when is a `py_library` not included in `site-packages` causing problems? Are you setting `imports` on your libraries?

**Comment by jvolkman** [comment] 2022-12-05 18:49
Hi @Paveltarno. Are you already using Bazel for these libraries (just not this package)? If so, are you setting the [imports](https://bazel.build/reference/be/python#py_library.imports) parameter?

**Comment by Paveltarno** [comment] 2022-12-05 21:16
Yes I am (as part of a poc) setting it to `[.]`

**Comment by jvolkman** [comment] 2022-12-06 21:40
@Paveltarno can you try again with #5 merged? With this change, `py_library` deps will be linked into `site-packages` if they specify `imports`.

**Comment by Paveltarno** [comment] 2022-12-07 09:36
looks like it works! perfect, thanks a lot @jvolkman

**Comment by jvolkman** [comment] 2022-12-07 17:57
Great. In that case I'm going to close this as resolved. Thanks for confirming!

**Closed by jvolkman** 2022-12-07 17:57 UTC
